Type inference bug fix
csarofeen/pytorch pull request #1443
Opened 2022-02-08 23:55 UTC by zasdfgbnm

It is important that the type inference code compute dim correctly because type promotion logic uses dim information. Currently, our type inference code just assigning `c10::nullopt` for dim, which causes bugs not detected by unit tests.

The unit tests that are supposed to test these cases were skipped because of the poor numerics of half, and bfloat16. In this PR, I reenable these tests, but only for dtypes.

I am pretty sure this PR does not fix all bugs, I will submit follow-up PRs for the remaining bugs.

Fixes https://github.com/csarofeen/pytorch/issues/1437

2022-02-09 00:23 UTC, rdspring1 approved these changes
LGTM

2022-02-09 18:31 UTC, jjsjann123 commented
> It is important that the type inference code compute dim correctly because type promotion logic uses dim information. Currently, our type inference code just assigning c10::nullopt for dim, which causes bugs not detected by unit tests.

Dumb question, did changes in type inference actually fixes anything??

> our type inference code just assigning c10::nullopt for dim,

This is done explicitly by design, we used to have shape propagation in this function, but that was pulled out since we now uses this for all shape propagation: https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/codegen/cuda/manager.cpp#L185

2022-02-09 19:31 UTC, zasdfgbnm commented
> Dumb question, did changes in type inference actually fixes anything??

It does. The fixed bug is https://github.com/csarofeen/pytorch/issues/1437. The root cause for this bug is the following:

In `at::native::result_type`
```c++
ScalarType result_type(const ResultTypeState& in_state) {
  return combine_categories(in_state.dimResult, combine_categories(in_state.zeroResult, in_state.wrappedResult));
}
```
it combines the result from `dimResult`, `zeroResult`, and `wrappedResult`, and in the type inference code, we have
```C++
at::native::ResultTypeState updateResultTypeState(
    OperandType tensor,
    const at::native::ResultTypeState& in_state) {
  at::native::ResultTypeState new_state = in_state;
  c10::ScalarType current = tensor.scalar_type;

  if (tensor.dim > 0) {
    new_state.dimResult =
        promoteTypesSkipUndefined(in_state.dimResult, current);
  } else {
    new_state.zeroResult =
        promoteTypesSkipUndefined(in_state.zeroResult, current);
  }
  return new_state;
}
```
without `tensor.dim` correctly set,  `updateResultTypeState` will incorrectly set `dimResult` instead of `zeroResult`, which causes wrong results.

> This is done explicitly by design, we used to have shape propagation in this function, but that was pulled out since we now uses this for all shape propagation: https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/codegen/cuda/manager.cpp#L185

If this is the case, I think we need to pull the dim info from shape propagation and use that info to set the `dim` correctly. But how do I access these information? I remember trying to print something like `node->output()->cast<TensorType>()->dim()` inside `binary_type` and get `nullopt`.

2022-02-09 19:47 UTC, jjsjann123 commented
Thanks for pointing out the context, forgot that we have scalar tensor have special type promotion logic. :face_exhaling: 

So the reason that shape information are wiped out is because that type_inference explicitly overwrites shape information. If you look at the pattern we have here, you'll see lots of `TensorType::create(*op->scalarType(), *op->device(), c10::nullopt, c10::nullopt);`, those should all be updated to forward the existing shape/stride that has already been on the tensor types.

One more thing to add is to clean up the shape propagation pass, I think the one after type inference can be removed as well.
https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/codegen/cuda/manager.cpp#L185

I do like the updates despite this `computeDimForBinaryOp`. :stuck_out_tongue_closed_eyes: 

Sorry this starts to look a lot more like code cleaning that's due on our part. How do you want to proceed this? Would be more than welcomed if you want to clean type_inference part up. Otherwise, I can push a refactor to your PR directly (ETA would be ~ end of Thursday / Friday morning).

2022-02-09 19:55 UTC, zasdfgbnm commented
I will do the cleanup in this PR directly. And I will ping you if I need help :)

2022-02-09 20:22 UTC, jjsjann123 requested changes
marking request changes to avoid accidental merge.

2022-02-11 16:48 UTC, csarofeen commented
Requesting re-review to reflect requested changes.

2022-02-11 19:50 UTC, zasdfgbnm commented
This should be ready

2022-02-15 22:05 UTC, jjsjann123 approved these changes
Thanks a lot for cleaning up for us :heart: 
LGTM

2022-02-15 22:05 UTC, jjsjann123 commented on torch/csrc/jit/codegen/cuda/type_inference.cpp
> +  TORCH_INTERNAL_ASSERT(out != nullptr);
nitpick: would be nice to have a message attached.

2022-02-15 22:05 UTC, jjsjann123 commented on torch/csrc/jit/codegen/cuda/type_inference.cpp
> +    auto out = node->output()->type()->cast<TensorType>();
nitpick: this could be changed to `copyScalarTypeAndDeviceToOutput(op, out)`.

2022-02-15 22:05 UTC, jjsjann123 commented on torch/csrc/jit/codegen/cuda/type_inference.cpp
> +    auto out = node->output()->type()->cast<TensorType>();
ditto.

2022-02-16 19:21 UTC, merged