Add leaky_relu operation
csarofeen/pytorch pull request #1852
Opened 2022-07-21 01:58 UTC by rdspring1

Fixes #1849

2022-07-21 05:58 UTC, jjsjann123 commented on torch/csrc/jit/codegen/cuda/parser.cpp
> +            if (node->input(1)->node()->kind() != prim::Constant) {
Looks like we are requiring input(1) to be constant here, but in the implementation above seems like we can take runtime input. Let's remove this line here.

2022-07-21 05:59 UTC, jjsjann123 requested changes
minor change requested

2022-07-22 12:38 UTC, csarofeen approved these changes
LGTM

2022-07-22 13:59 UTC, jjsjann123 approved these changes
LGTM, thanks for the update~~

2022-07-22 15:32 UTC, merged