TensorView Factory
csarofeen/pytorch pull request #410
Opened 2020-10-07 14:26 UTC by csarofeen

Similar to how we construct tensors with ATen with TensorOptions like:
```.cpp
  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  auto t0 = at::randn({16, 16, 8}, options);
```
I added a similar factory construction to our TensorViews:
```.cpp
TensorView* makeSymbolicTensor(int ndims, DataType dtype = DataType::Float) {
  return TensorView::makeTensor(
      TensorViewOptions().nDims(ndims).fullySymbolic(true).DType(dtype));
}
```

Still need to add documentation on this.

2020-10-08 16:45 UTC, tlemo requested changes

2020-10-08 16:45 UTC, tlemo commented on torch/csrc/jit/codegen/cuda/ir_interface_nodes.h
> +/**
Please use `//!` exclusively for Doxygen comments (see the Doxygen guideline document)

2020-10-08 16:45 UTC, tlemo commented on torch/csrc/jit/codegen/cuda/ir_interface_nodes.h
> +  /// Set the number of dimensions of the tensor
ditto: use `//!` consistently instead of `///`

2020-10-08 16:45 UTC, tlemo commented on torch/csrc/jit/codegen/cuda/ir_interface_nodes.h
> +  TensorViewOptions DType(DataType dtype) const {
`DType` doesn't seems to follow the naming style. In PyTorch style this should be `dtype` (which also matches `TensorOptions::dtype`)

2020-10-08 16:45 UTC, tlemo commented on torch/csrc/jit/codegen/cuda/ir_interface_nodes.h
> +  TensorViewOptions nDims(int ndims) const {
it seems we could use `C10_NODISCARD` for these builder methods

2020-10-08 16:45 UTC, tlemo commented on torch/csrc/jit/codegen/cuda/ir_interface_nodes.h
> +class TensorViewOptions {
this class could be final

2020-10-08 16:45 UTC, tlemo commented on torch/csrc/jit/codegen/cuda/ir_interface_nodes.h
> +    TensorViewOptions tvo = *this;
I can see this pattern has been copied from TensorOptions, but I see no reason why we can't be more concise:

```
ndims_ = ndims;
return *this;
```

2020-10-08 16:45 UTC, tlemo commented on torch/csrc/jit/codegen/cuda/ir_interface_nodes.h
> + protected:
1. why protected and not private?
2. private (or protected) data should the last section in the class definition

2020-10-08 16:45 UTC, tlemo commented on torch/csrc/jit/codegen/cuda/ir_interface_nodes.h
> +  int n_dims = 1;
naming: all the private/protected data members should use the `_` suffix

2020-10-08 16:45 UTC, tlemo commented on torch/csrc/jit/codegen/cuda/ir_interface_nodes.h
> +  void setNDims(const int ndims) {
what is the role of these private helpers?

2020-10-08 16:45 UTC, tlemo commented on torch/csrc/jit/codegen/cuda/ir_interface_nodes.h
> +/**
comment style

2020-10-08 16:45 UTC, tlemo commented on torch/csrc/jit/codegen/cuda/ir_interface_nodes.h
> +
nit: no need for empty line here (also //! instead of ///)

2020-10-28 20:07 UTC, csarofeen commented
closed in favor of https://github.com/csarofeen/pytorch/pull/410

2020-10-28 20:07 UTC, closed without merging