[WIP] Cache Read
csarofeen/pytorch pull request #91
Opened 2020-06-17 15:32 UTC by rdspring1

Add [cache read](https://docs.tvm.ai/api/python/schedule.html#tvm.schedule.Schedule.cache_read) support.

- [X] Insert new TensorView Reader before current TensorView 
 e.g. For `TV2 = TV1.cache_read();` insert `TV2` before `TV1`
- [ ] ComputeAt support - Call `TV2->computeAt(TV1, axis)` if there is a `computeAt` on `TV1`
- [ ] Add option to set memory space for TensorView
- [ ] Support for static shared_memory allocation

2020-06-19 21:43 UTC, csarofeen requested changes

2020-06-19 21:43 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +  auto dom = domain()->noReductions();
shouldn't be done on domain, should be done on root domain.

2020-06-19 21:43 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +          new Int(0), new Int(1), ParallelType::Serial, false, false, true);
If it's a broadcast dimension just ignore it.

2020-06-19 21:43 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +      out_domain[i] = new IterDomain(dom[i]->start(), dom[i]->extent());
No reason not to copy over all information that isn't broadcast and reduction. I think just parallel type is left, but check.

2020-06-19 21:43 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +    producer->computeAt(consumer, getThisComputeAtAxis());
Once the above is fixed this should be fine.

You also need to run through tensors and find if anything was set to computeAt into this tensor, and redo it computeAt-ed into the new tensor.

I'm uncertain exactly how the computeAt position argument matches up, please think through it carefully, as computeAt axes can change based on producer consumer relationships and if there are reductions/broadcasts within the computeAt axis.

2020-06-19 21:43 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +      uses_expr.size() > 0,
Using cache_after on a tensor shouldn't necessarily be bad if it's on a tensor view without a use as long as it's not an output. I think for now it's restrictive enough to make sure it's not an output.

I'm wondering if there may be uses to do a cache_after and then make the result an output.

Similar for cache_before/inputs.

2020-06-19 21:43 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +  auto dom = domain()->noReductions();
not on domain, on getRootDomain()

2020-06-19 21:43 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +    if (dom[i]->isBroadcast()) {
If we have a broadcast dimension then we need to actually remove the broadcast dimension from this tensor but propagate it to the next one.

Before we do this you need to grab the computeAt information to be able to reconstruct it.

We also need to run through tensors that are computeAt into us and redo them.

2020-06-19 21:43 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +    case ExprType::Split:
Use one of the dispatch mechanisms in dispatch.h you can find many examples of usage in the code base.

2020-06-19 21:43 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +    case ExprType::Split:
Just a warning that I didn't carefully look at below.

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +  // After: Prev Op -> New Cache_Read Op -> This Op
please use consistent names. I think here you mean
Before: `origin_op -> this TV`
After: `origin_op->cached read TV -> set Op -> this TV`

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +          origin_input->getComputeAtView()->sameAs(this)) {
you can directly use `==` here

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +        origin_input->computeAt(this, axis);
Looks good.

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +    producer->computeAt(this->getComputeAtView(), axis);
looks good

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +  // After: This Op -> New Cache_Write Op -> Next Op
Same as above.

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +
Sorry, having trouble understanding what is going on in the code block above this comment.

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +    this->computeAt(this->getComputeAtView(), axis);
this looks good.

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +          origin_input->getComputeAtView()->sameAs(this)) {
you can just use `==` here

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +// Create New Expr given consumer - [output of the expression]
Can you put something more explicit like:
We want expr to be replaced where the output where `current` is located will be `consumer`

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +    CreateExprConsumer dispatch(current, consumer);
nit, usually I just name the instance something like the initials i.e. `cec`

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +struct CreateExprConsumer : public OptOutDispatch {
This should be OptInDispatch, so if it's passed an expr it doesn't recognize it errors instead of doing nothing.

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +struct CreateExprProducer : public OptOutDispatch {
This should be OptInDispatch, so if it's passed an expr it doesn't recognize it errors instead of doing nothing.

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +      TransformReplay::replayPasC(consumer_, current_, current_->getThisComputeAtAxis());
I don't think you need this, if you do it should go after the reductionOp.

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +      TransformReplay::replayPasC(consumer_, current_, current_->getThisComputeAtAxis());
I don't think you need this, but if you do it should go after the broadcast op.

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +      TransformReplay::replayCasP(producer_, current_, current_->getThisComputeAtAxis());
I don't think you need this, if you do it should go after the reductionOp.

2020-07-08 00:21 UTC, csarofeen commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +      TransformReplay::replayCasP(producer_, current_, current_->getThisComputeAtAxis());
I don't think you need this, if you do it should go after the broadcastOp.

2020-07-08 04:21 UTC, rdspring1 commented on torch/csrc/jit/codegen/cuda/tensor_view.cpp
> +  // After: Prev Op -> New Cache_Read Op -> This Op
I went with this instead:
```
  Before: Prev TV -> [Origin Op] -> This TV
  After:  Prev TV -> [Origin Op] -> New Cache_Before TV -> [Set Op] -> This TV
```

2020-07-11 03:33 UTC, closed without merging